# Generated by Django 5.2.5 on 2025-12-02 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=100)),
                ('tipo_vivienda', models.CharField(max_length=50)),
                ('tiene_mascotas', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('estado_salud', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='animales/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HogarTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=255)),
                ('capacidad_animales', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuenta', models.CharField(max_length=70, unique=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('contraseña', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('id_adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adoptante')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(upload_to='contratos/')),
                ('firma_adoptante', models.BooleanField()),
                ('firma_admin', models.BooleanField()),
                ('id_adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adopcion')),
                ('id_adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunas', models.CharField(max_length=255)),
                ('esterilizado', models.BooleanField()),
                ('fecha_control', models.DateField()),
                ('observaciones', models.CharField(max_length=255)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='id_hogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.hogartemporal'),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comprobante', models.ImageField(upload_to='comprobantes/')),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='adoptante',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuario'),
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voluntariado', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='hogartemporal',
            name='id_voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.voluntario'),
        ),
        migrations.CreateModel(
            name='EntrevistaVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=20)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_entrevista_vol', to='mainApp.usuario')),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.voluntario')),
                ('id_voluntario_entr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vol_entrevista_vol', to='mainApp.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=20)),
                ('id_adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adopcion')),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.usuario')),
                ('id_voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.voluntario')),
            ],
        ),
    ]
