# Generated by Django 5.2.5 on 2025-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('voluntario', 'Voluntario'), ('adoptante', 'Adoptante'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
