# Generated by Django 5.2.5 on 2025-12-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_usuario_direccion_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(choices=[('perro1', '🐕 Perro 1'), ('perro2', '🦮 Perro 2'), ('perro3', '🐩 Perro 3'), ('gato1', '🐈 Gato 1'), ('gato2', '🐱 Gato 2'), ('gato3', '😺 Gato 3'), ('conejo', '🐰 Conejo'), ('hamster', '🐹 Hamster'), ('loro', '🦜 Loro'), ('tortuga', '🐢 Tortuga')], default='perro1', max_length=20),
        ),
    ]
