# Generated by Django 5.2.5 on 2025-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='fecha_control',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='vacunas',
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='estado_salud',
            field=models.CharField(default='Bueno', max_length=100),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='fecha_esterilizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='proximo_control',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='ultima_vacunacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='ultimo_control',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='vacunas_al_dia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='esterilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
