# Generated by Django 5.2.5 on 2025-12-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_update_fichamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='fecha_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='fecha_entrevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='link_zoom',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='observaciones_entrevista',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_procesadas', to='mainApp.usuario'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='url_formulario_google',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='acepta_seguimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='compromiso_cuidado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma_admin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma_adoptante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Solicitud Pendiente'), ('entrevista_agendada', 'Entrevista Agendada'), ('entrevista_realizada', 'Entrevista Realizada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('contrato_generado', 'Contrato Generado'), ('completada', 'Adopción Completada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='firma_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='firma_adoptante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='id_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichamedica', to='mainApp.animal'),
        ),
    ]
