# Generated by Django 5.2.5 on 2025-12-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_adopcion_fecha_aprobacion_adopcion_fecha_contrato_and_more'),
    ]

    operations = [
        # Modificar id_usuario para que sea nullable
        migrations.AlterField(
            model_name='adoptante',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        
        # Agregar todos los campos nuevos del formulario de adopción
        migrations.AddField(
            model_name='adoptante',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='foto_carnet',
            field=models.ImageField(blank=True, null=True, upload_to='carnets/'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='es_extranjero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_residencia_definitiva',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='comuna',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='por_que_adoptar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_o_tuvo_mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='mascotas_esterilizadas_vacunadas',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='alimento_mascotas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='miembros_familia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='decision_compartida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='es_alergico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='medidas_alergia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_mallas_proteccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='permiten_mascotas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tiene_recursos_economicos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='que_pasa_si_mudanza',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='acepta_videollamada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='acepta_seguimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='acepta_enviar_fotos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='acepta_tenencia_indoor',
            field=models.BooleanField(default=True),
        ),
        
        # Crear modelo SolicitudVoluntariado
        migrations.CreateModel(
            name='SolicitudVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('equipo', models.CharField(choices=[('veterinaria', 'Veterinaria'), ('peluqueria', 'Peluquería'), ('rescatistas', 'Rescatistas'), ('diseno', 'Diseño'), ('tallerista', 'Tallerista'), ('hogar_temporal', 'Hogar Temporal')], max_length=50)),
                ('experiencia_previa', models.TextField()),
                ('motivacion', models.TextField()),
                ('informacion_adicional', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entrevista_agendada', 'Entrevista Agendada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('fecha_entrevista', models.DateTimeField(blank=True, null=True)),
                ('link_zoom', models.URLField(blank=True)),
                ('observaciones_admin', models.TextField(blank=True)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

