# Generated by Django 5.2.5 on 2025-12-02 23:40

import django.db.models.deletion 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_update_adoptante_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuario'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='equipo',
            field=models.CharField(choices=[('veterinaria', 'Veterinaria'), ('peluqueria', 'Peluquería'), ('rescatistas', 'Rescatistas'), ('diseno', 'Diseño gráfico'), ('tallerista', 'Tallerista'), ('hogar_temporal', 'Hogar Temporal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entrevista_agendada', 'Entrevista Agendada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='informacion_adicional',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='link_zoom',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='observaciones_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitudvoluntariado',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_voluntariado_procesadas', to='mainApp.usuario'),
        ),
    ]
