# Generated by Django 5.2.5 on 2025-12-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_add_missing_adoptante_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='tiene_mascotas',
        ),
        migrations.AddField(
            model_name='solicitudvoluntariado',
            name='usuario_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_voluntariado', to='mainApp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(choices=[('perro', '🐕 Perro'), ('gato', '🐱 Gato'), ('pajaro', '🦜 Pájaro'), ('chanchito', '🐷 Chanchito'), ('rata', '🐭 Rata'), ('caballo', '🐴 Caballo'), ('conejo', '🐰 Conejo'), ('tortuga', '🐢 Tortuga'), ('vaca', '🐮 Vaca'), ('dinosaurio', '🦖 Dinosaurio')], default='perro', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuario')),
            ],
        ),
    ]
