# Generated by Django 5.2.5 on 2025-12-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_adoptante_ocupacion_and_more'),
    ]

    operations = [
    ]
