# Generated by Django 5.2.8 on 2025-12-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_actualizar_adoptante_fotos_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='fecha_solicitud',
            new_name='fecha_adopcion',
        ),
        migrations.RenameField(
            model_name='adopcion',
            old_name='fecha_aprobacion',
            new_name='fecha_completada',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='foto_carnet',
            new_name='foto_carnet_frontal',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='fecha_entrevista',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='link_zoom',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='observaciones_entrevista',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='procesado_por',
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='url_formulario_google',
        ),
        migrations.RemoveField(
            model_name='solicitudvoluntariado',
            name='link_zoom',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones_aprobadas', to='mainApp.usuario'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='foto_carnet_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='carnets/'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('contrato_generado', 'Contrato Generado'), ('completada', 'Adopción Completada')], default='en_proceso', max_length=30),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Solicitud Pendiente'), ('entrevista_agendada', 'Entrevista Agendada'), ('entrevista_realizada', 'Entrevista Realizada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_entrevista', models.DateTimeField(blank=True, null=True)),
                ('observaciones_entrevista', models.TextField(blank=True, default='')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('id_adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adoptante')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.animal')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_adopcion_procesadas', to='mainApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='solicitud_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopcion_creada', to='mainApp.solicitudadopcion'),
        ),
    ]
